---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Image
      shell: docker pull anshul1601/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator anshul1601/calculator
